<a href="https://colab.research.google.com/github/keehyun0613/basic/blob/master/numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.zeros((2, 4), dtype=float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2, 4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.random.rand(2,4)     #(0, 1)범위에서 균등분포에 따른 난수

array([[0.84915528, 0.44871413, 0.55699818, 0.33130786],
       [0.55711271, 0.28988164, 0.97344128, 0.48252503]])

In [ ]:
np.random.rand(1)     #array형태

array([0.63737189])

In [ ]:
np.random.rand()     #상수형태

0.11826888293978621

In [ ]:
np.random.randn(2,4)     #표준정규분포에 따른 난수

array([[-0.63247514,  0.55859782,  0.45734538, -1.92559118],
       [-0.53755716, -1.8048949 , -1.28865383, -1.25181515]])

In [ ]:
np.random.randint(0, 20, (2,4))     #[0, 20]범위의 정수로 된 난수

array([[11, 16,  2,  3],
       [13,  7, 14, 15]])

In [ ]:
np.random.normal(1, 2, (2, 4))     #평균이 1, 표준편차가 2인 정규분포에 따른 난수

array([[0.1288184 , 0.03765897, 1.53873576, 2.64989326],
       [3.82712246, 1.865601  , 4.06107854, 1.05604376]])

In [ ]:
np.random.uniform(-2, 2, (2,4))     #(-2, 2)범위에서 균등분포에 따른 난수

array([[ 1.53612552,  0.51361293,  1.99351629,  1.66674269],
       [-1.35115497, -0.09457588, -0.68184489,  0.06951385]])

In [ ]:
np.random.choice(20, 3)     #[0, 20)범위의 정수 중에서 3개를 임의로 선택하여 나열한 array

array([ 3,  3, 12])

In [ ]:
np.random.choice(3, 5)     #[0, 3)범위의 정수 중에서 중복을 허락하여 5개를 임의로 선택하여 나열한 array

array([0, 1, 0, 2, 0])

In [ ]:
np.arange(0, 6, dtype=float)     #[0, 6)범위에서 1간격으로 나열

array([0., 1., 2., 3., 4., 5.])

In [ ]:
np.arange(0, 10, 2)     #[0, 10)범위에서 2간격으로 나열

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0, 5, 6, dtype=float)     #첫 항이 0, 마지막 항이 5이고 항수가 6개인 등차수열 나열

array([0., 1., 2., 3., 4., 5.])

In [ ]:
list = [1, 2, 3, 4, 5, 6]   ;    a = np.array(list, dtype=float)   ;   a     #list를 array로 변환

array([1., 2., 3., 4., 5., 6.])

In [ ]:
a1 = a.reshape(1, 3, 2)   ;   a1

array([[[1., 2.],
        [3., 4.],
        [5., 6.]]])

In [ ]:
a2 = np.squeeze(a1)   ;   a2     #1차원 부분을 삭제

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
np.squeeze(np.array([5]))     #상수로 변환

array(5)

In [ ]:
a3 = a2.T   ;    a3      #전치행렬

array([[1., 3., 5.],
       [2., 4., 6.]])

In [ ]:
a4 = a.reshape(1, 6).T   ;   a4      #벡터는 행렬로 바꾸고 전치

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [ ]:
row_add = np.array([-1, -2, -3]).reshape(1, 3)
a5 = np.concatenate((a3, row_add), axis=0)    ;   a5      #행방향으로 추가

array([[ 1.,  3.,  5.],
       [ 2.,  4.,  6.],
       [-1., -2., -3.]])

In [ ]:
col_add = np.array([[4, 5, 6], [7, 8, 9]]).T
a6= np.concatenate((a5, col_add), axis=1)    ;   a6      #열방향으로 추가

array([[ 1.,  3.,  5.,  4.,  7.],
       [ 2.,  4.,  6.,  5.,  8.],
       [-1., -2., -3.,  6.,  9.]])

In [ ]:
a6[:2, :-1]

array([[1., 3., 5., 4.],
       [2., 4., 6., 5.]])

In [ ]:
a6[2, 1]

-2.0

In [ ]:
a7 = a6[[0, 2]]    ; a7     #두 개의 데이터 선택

array([[ 1.,  3.,  5.,  4.,  7.],
       [-1., -2., -3.,  6.,  9.]])

In [ ]:
a8 = a6.astype(int)   ;    a8     #변수형을 정수로

array([[ 1,  3,  5,  4,  7],
       [ 2,  4,  6,  5,  8],
       [-1, -2, -3,  6,  9]])

In [ ]:
a9 = np.sort(a6)   ;  a9    #오름차순 정렬

array([[ 1.,  3.,  4.,  5.,  7.],
       [ 2.,  4.,  5.,  6.,  8.],
       [-3., -2., -1.,  6.,  9.]])

In [ ]:
b = np.arange(8).reshape(2, 4)   ;  b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
b1 = b<5    ; b1     #마스킹 연산

array([[ True,  True,  True,  True],
       [ True, False, False, False]])

In [ ]:
b2 = b.copy()    #그대로 복사할 떄는 b2 = b라 하면 안됨
b2[b1] = -1   ;   b2    #마스킹한 원소를 -1로 변형

array([[-1, -1, -1, -1],
       [-1,  5,  6,  7]])

In [ ]:
b3 = b + 2   ;  b3    #broadcast

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [ ]:
b4 = b * np.array([0, 1, 0, 1])    ;  b4     #broadcast

array([[0, 1, 0, 3],
       [0, 5, 0, 7]])

In [ ]:
c = np.arange(1, 9).reshape(4, 2)
b5 = np.dot(b, c)   ;  b5   #행렬곱 broadcast x

array([[ 34,  40],
       [ 98, 120]])

In [ ]:
np.max(b)     #전체에서 최대

7

In [ ]:
np.max(b, axis = 0)     #행 기준으로 최대

array([4, 5, 6, 7])

In [ ]:
np.argmax(b)     #전체에서 index

7

In [ ]:
np.sum(b, axis = 0)     #행 기준으로 합

array([ 4,  6,  8, 10])

In [ ]:
np.mean(b)    #전체 평균

3.5

In [ ]:
np.exp(b)     #밑이 e 지수가 b

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03]])

In [ ]:
np.power(b, 2)     #밑이 b 지수가 2

array([[ 0,  1,  4,  9],
       [16, 25, 36, 49]])

In [ ]:
np.sqrt(b)     #루트 b

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131]])

In [ ]:
np.log(b + 1)    #자연로그, 밑이 2인 로그는 np.log2(b + 1)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154]])